//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourney.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Tournament> Tournaments { get; set; }
    }
}
