//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourney.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public Nullable<int> LoserId { get; set; }
        public bool IsDraw { get; set; }
        public bool IsForfeit { get; set; }
        public int EventId { get; set; }
        public Nullable<int> RoundId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
        public virtual Round Round { get; set; }
    }
}
